apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
  namespace: nsync
  labels:
    app: notification
    app.kubernetes.io/part-of: notification
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: notification-service
