spring:
  rabbitmq:
    host: '#{RABBITMQ_HOST}'
    port: #{RABBITMQ_PORT}
    username: '#{RABBITMQ_USER}'
    password: '#{RABBITMQ_PASSWORD}'
    ssl:
      enabled: false

app:
  async:
    withDLQRetry: true
    createTopology: false
    domain:
      events:
        exchange: #{EVENT_EXCHANGE}
        maxLengthBytes: 125000000
        retry:
          maxAttempts: 3
          initialInterval: 1000
          multiplier: 1.5
          maxInterval: 10000